# WhatATheme
markdown: kramdown

# URL of the Site
url: 'https://cbailey603.github.io'
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: '/Portfolio'

# Title of the Site
title: Connor Bailey's Portfolio
# Description of the Site
description: Data Analysis and Visualization
# URL of Image of the Site
site-image: https://cbailey603.github.io/Portfolio/assets/images/headshot.jpg
# Keywords of the Site
site-keywords: Site, Template, Theme
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: https://cbailey603.github.io/Portfolio/assets/images/boston.jpg

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: connorrichardbailey603@gmail.com
facebook_username:
twitter_username:
instagram_username:
linkedin_username: connor-bailey-829942a9
github_username: cbailey603
youtube_channel_id: 
reddit_username: 
behance_username: 
dribbble_username: 
spotify_username: 

# Google Analytics
google-analytics: UA-163806439-1

# Disqus
disqus-shortname: thedevslot

# Name of the Author
author-name: Connor Bailey
# URL for the Image of the Author
author-image: https://cbailey603.github.io/Portfolio/assets/images/me.jpg
# 60 Words About the Author
author-about: Hellow World! I am a data analyst with a background in applied economics and eletrical engineering. I obtained my B.S. in Electrical Engineering from the University of Connecticutt in 2016 and worked in product development until 2021. I decided to change the trajectory of my career by going back to school for economics and data analysis. I enrolled at Boston College in 2022, finishing in 2023 with an M.S in Applied Economics and a Data Analysis Certificate. I am currently looking to apply my talents in data analysis!
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/cbailey603

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
